version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-recipes_db}
      POSTGRES_USER: ${POSTGRES_USER:-recipes_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-recipes_password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-recipes_user} -d ${POSTGRES_DB:-recipes_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Django Web Application
  web:
    build: .
    restart: unless-stopped
    volumes:
      # For development - live code reloading
      - .:/app
      # Persistent media files
      - media_files:/app/media
      # Static files
      - static_files:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-recipes_user}:${POSTGRES_PASSWORD:-recipes_password}@db:5432/${POSTGRES_DB:-recipes_db}
      - DB_NAME=${POSTGRES_DB:-recipes_db}
      - DB_USER=${POSTGRES_USER:-recipes_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-recipes_password}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin123}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  redis_data:
  media_files:
  static_files:

networks:
  default:
    name: recipes_network