FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        build-essential \
        libpq-dev \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . /app/

# Create media directory
RUN mkdir -p /app/media
RUN ls -l /app
# Collect static files
RUN python manage.py collectstatic --noinput

# Make entrypoint executable
# COPY entrypoint.dev.sh /app/
# RUN chmod +x /app/entrypoint.dev.sh

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.dev.sh"]