version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./media:/app/media
      # - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ENV=local

    networks:
      - recipes_network
   

volumes:
  media_volume:

networks:
  recipes_network:
    driver: bridge